theme: jekyll-theme-slate
permalink: /:categories/:year/:month/:day/:title
title: Jan Beernink

paginate: 25

defaults:
  -
    values:
      author: Jan Beernink
      layout: default
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-titles-from-headings

feed:
  tags: true
  categories:
    - OmniServices
    - OmniUtils
