= String Templates - Part One
Jan Beernink
:jbake-type: post
:jbake-tags: java-21, string-templates, jdk-preview-feature
:jbake-status: draft
:tabsize: 2
:icons: font
:sourcedir: ../../../java/eu/jbeernink/blog/jdk21/stringtemplates
:source-highlighter: highlight.js

String interpolation is a powerful feature by many languages. Instead of using String concatenation or using variable substitution on special format strings. Statements can inlined into the string itself, which is easier to read and less verbose than using string concatenation.

String interpolation also avoids some of the issues with using format strings. Using format strings often requires keeping the values to insert into the strings in the same order as they are used, or to explicitly specify the index of the value to insert, which can be error prone. Swap two values to be inserted around by accident and your produced string is incorrect, or worse, causes an error at runtime. This is also the reason we added the https://github.com/omnifaces/omniutils/blob/develop/src/main/java/org/omnifaces/utils/text/NameBasedMessageFormat.java[NameBasedMessageFormat class] in the https://github.com/omnifaces/omniutils[OmniUtils project], which allows substitute strings to be identified by names rather than their position in the arguments.

The power of string interpolation does have some drawbacks, though. The ease of use of String interpolation may tempt some developers to use it in ways that are inherently dangerous. For example, it may be tempting to use string interpolation to build an SQL statement. If the input values are not properly escaped, using string interpolation may lead to SQL injection exploits.

== String templates

Java 21 adds a new preview language feature for string interpolation in the form of https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/StringTemplate.html[StringTemplates]. Just like typical string interpolation, a `StringTemplate` is a hard-coded string containing code statements which are evaluated to a value at runtime. The main benefit of a `StringTemplate` over typical string interpolation, is that it also supports additional processing, including escaping, on the input values. A `StringTemplate` also does not necessarily need to produce a `String`, but it can produce any type of object, for example, a `StringTemplate` could be evaluated directly to a `java.sql.PreparedStatement` when creating an SQL statement.

How the `StringTemplate` is processed and what type of object is produced is determined by a `StringTemplate.Processor`. These processors are the core of the `StringTemplate` feature. These classes are responsible for taking the hardcoded strings sequences and values and performing any processing on these.

The syntax for using string templates, is quite similar to using a regular string, but with a twist. Using a string template requires a processor followed by a `.` operator and then the string or text block template. Any statements in the template are denoted by a sequence starting with the new `\{` escape sequence and ending with the matching `}`. To put this all together, using a string template ends up looking something like this:

[source,java,indent=0]
----
include::{sourcedir}/StringTemplateDemo.java[tag=syntax]
----
<1> The resulting string would be `"1 + 2 = 3"`, when using a processor doing simple string interpolation.

It is also possible to use text block templates with a very similar syntax. The only difference is using `"""` to denote the start and end of a string. With a text block template, all the usual rules apply for removing empty space in the string. This would give an example looking like this:

[source,java,indent=0]
include::{sourcedir}/StringTemplateDemo.java[tag=textBlockTemplate]


=== Processors

The processors are where all the work happens, they take a `StringTemplate` instance as argument and produce an object. The fact that a processor can produce any kind of object makes string templates a very flexible feature when compared to regular string interpolation. JDK 21 ships with three different processors:

* https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/StringTemplate.html#STR[`StringTemplate.STR`]
* https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/util/FormatProcessor.html#FMT[`FormatProcessor.FMT`]
* https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/StringTemplate.html#RAW[`StringTemplate.RAW`]

`StringTemplate.STR` is a simple processor that does "plain" string interpolation. It inserts any values directly into the string, without performing any other processing. `STR` will be imported by default in any class, so no additional imports are required to use it.

[source,java,indent=0]
----
include::{sourcedir}/StringTemplateDemo.java[tag=strProcessorExample]
----
<1> If the `name` variable was set to `"world"`, for example, this would produce the string `"Hello, world"`.

The `FormatProcessor.FMT` processor uses the same specification as the https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/util/Formatter.html[`Formatter`] class (or https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/String.html#format(java.util.Locale,java.lang.String,java.lang.Object...)[`String.format()`]) to format the values to be inserted. Unlike `Formatter` and `String.format(), the `FMT` processor does not use the position in the arguments but instead inlines the statements directly. Say we wanted to format a number as a 2-character wide hexadecimal string with a leading zero used as padding, we could achieve this with the `FMT` processor like so:

[source,java,indent=0]
----
include::{sourcedir}/StringTemplateDemo.java[tag=fmtProcessorExample]
----
<1> If `number` was set to 15, this would produce the string `"0F"`.

The last processor, `StringTemplate.RAW` works quite different from the first two. Rather than returning a string, this processor will return a `StringTemplate` instance itself. In JDK 21, this is the only way to obtain instances of `StringTemplate` directly. The `StringTemplate` instance itself is immediately passed to the processor when using either the `STR` or `FMT` processors, the calling code never sees the `StringTemplate` instance directly.

== Conclusion

This was just a quick dive into the new string template feature which is introduced as a preview feature in JDK 21. In a follow-up post, I will dive deeper into what is required to write a template processor and what is possible with these processors.
