= Trying out String Templates in JDK 21 - Part One
Jan Beernink
:jbake-type: post
:jbake-tags: java-21, string-templates, jdk-preview-feature
:jbake-status: draft

JDK 21 adds https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/StringTemplate.html[String Templates] as a preview feature. String Templates are Java's solution for String interpolation. While String interpolation can be very useful, it is very tempting to use it for use cases where it can introduce safety issues. Consider for example an SQL query, with String interpolation, the input string is usually inserted directly into the string, without any escaping.

Consider, for example, the below pseudo-code

```java
String sqlStatement = """
   SELECT
     *
   FROM
     Users u
   WHERE
     u.firstName = "${firstNameInput}"
   """;

return connection.execute(sqlStatement);
```

If `firstNameInput` is provided directly by the user, this would allow a malicious actor to perform SQL injection using a specifically prepared input string. This malicious actor could force the UI to return all users, which could potentially expose personally identifiable information (PII) or even delete or corrupt data in the database.

String Templates aim to provide an alternative for this, rather than directly inserting the value of a statement into a string literal. To achieve this, the String Template feature consists of two parts:

 * A https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/StringTemplate.html[StringTemplate]
 * A https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/lang/StringTemplate.Processor.html[StringTemplate.Processor]

`StringTemplate` instances can currently (as of the JDK 21 pre-release builds) only be created in combination with an instance of a `StringTemplate.Processor`, using new syntax introduced in JDK 21. Within a `StringTemplate`, a new escape sequence is introduced (`\{`) to start an expression (with `}` serving as the end of the expression). This new escape sequence is currently illegal in existing `String` code. This means that this new escape sequence will not clash with existing code. For example, if you have some code that outputs a sequence of code in another language, there is no way that the `StringTemplate` escape sequence will clash with this.

The `StringTemplate.Processor` is where all the work happens. The processor will accept the raw `StringTemplate` with all the statements in the template evaluated and will then perform parsing and substition.

One example of such a processor is https://download.java.net/java/early_access/jdk21/docs/api/java.base/java/util/FormatProcessor.html#FMT[FormatProcessor.FMT]. This processor basically does the same a `String.format()`, but uses inline code statements instead of an argument to provide formatting. Consider the following example:

```java
var name = "world";
String.format("Hello, %s!, name);
```

Using the `FMT` processor, we would rewrite this as:
```java
var name = "world";
FMT."Hello, \{name}!";
```

One particularly powerful feature of the template processors is that they do not have to output a String, in fact, the result can be any type of object.

TODO
 - finish article
 - rewrite sections, should be more easy to comprehend.
